services:
  - type: web
    name: trackwise-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: trackwise_super_secret_key
      - key: MONGO_URI
        value: mongodb+srv://suthis3003_db_user:FT6eumx6ybk2nGFX@cluster0.5d1bguf.mongodb.net/trackwise?retryWrites=true&w=majority&appName=Cluster0
